### PR TITLE
Implementing a receiver branch on scaffold eth

### PR DESCRIPTION
**Pull request by BrianS111**
Implemented A receiver item onto the Scaffold ETH navbar which has instructions on how to install receiver on to a website following styling from https://react.relay.cc/dynamic, and the readme from https://github.com/relaycc/receiver/edit/main/README.md

### CODE REVIEW

**Comment by BrianS111** [comment]
https://www.notion.so/relaycc/Scratch-Pad-6691609cbf204823986a4cb40548a317

**Comment by killthebuddh4** [comment]
@BrianS111 Please add @andrewvdp and @seandaopanel as reviewers. If you could take a screencap video of clicking through all the stuff you added that would help a lot as well.

**Comment by andrewvdp** [comment]
@BrianS111 i would remove all the unneeded changes to whitespace / indentation. It makes for a diff that is much easier to review

**Comment by BrianS111** [comment]
> @BrianS111 Please add @andrewvdp and @seandaopanel as reviewers. If you could take a screencap video of clicking through all the stuff you added that would help a lot as well.

**Comment by seandaopanel** [comment]
re: tabs..can we consolidate the smart contract tabs into one? This is meant for hackathons so useful to leave in I think

**Pull request closed without merging**
