### PR TITLE
Implementing a receiver branch on Scaffold eth

### PR DESCRIPTION
**Pull request by BrianS111**

### CODE REVIEW

**Comment by BrianS111** [comment]
Implemented A receiver item onto the Scaffold ETH navbar which has instructions on how to install receiver on to a website following styling from https://react.relay.cc/dynamic, and the readme from https://github.com/relaycc/receiver/edit/main/README.md

**Comment by BrianS111** [comment]
https://www.notion.so/relaycc/Scratch-Pad-6691609cbf204823986a4cb40548a317

**Comment by BrianS111** [comment]
I will be uploading a demo video shorty

**Comment by BrianS111** [comment]
D1936042-2EC1-48E9-9EA6-14F8CBEB4D60_1_102_o

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/191354498-d9fc2c12-f485-4be7-af7a-8b26056041bd.mov

**Review by andrewvdp — APPROVED** [review]

**Review by killthebuddh4 — APPROVED** [review]
@BrianS111 @seandaopanel @andrewvdp I think this is fine, but the vertical flow is kind of confusing. The bullet points starts with a UX tip, then goes into an install/build step, then back into a UX tip. The "Dynamic Addresses" header is confusing because users will have no clue what a "dynamic" address is. From there flowing into the README seems kinda odd. 

I'm not really sure what type of review I should be doing in this case but I'm approving because it looks like it works and I don't really have much context on what the goals are for this PR.

**Comment by killthebuddh4** [comment]
@andrewvdp @seandaopanel @BrianS111 What's the next step with this? Is it in fact approved and ready to merge into the original?

**Comment by andrewvdp** [comment]
@seandaopanel I know we were going to make some adjustments to get closer to the punkwallet model. Did we complete all those changes?

**Comment by seandaopanel** [comment]
The point of this is to be an excellent starting point for devs at hackathons. Most Gitcoin/Ethglobal hackers are recommended to start with the scaffold-eth app, for the speedup it gives. 

This will add a Relay Receiver chatbox to the starterkit, so chat works out of the box. Instructions are provided in how to configure the launcher style/button. 
@killthebuddh4 The language of it could be made for clear for this purpose? The 3 steps you said in #xmtp
@andrewvdp we don't need to make it like punkwallet, that was just for context. Working off of master is best, so we'll keep all the info in other sections.

**Comment by BrianS111** [comment]
This post needs adjusting as it no longer accurately descries the receiver components. I can adjust it to receiver 0.1.53 which is the current one, but it appears a big update is in the process if we are making it draggable with profile functionality, so maybe the post should hold off until that version is released?

**Comment by killthebuddh4** [comment]
Closing this for now. Will re-open if necessary.

**Pull request closed without merging**
